services:
  db:
    image: mysql:8.0.36
    container_name: jastip_mysql_core
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jastip_dev
      MYSQL_USER: jastip_user
      MYSQL_PASSWORD: jastip_password
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
